// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJLMQEXpqyWLVssWyDmlYoNXs0ZD9WkqA',
    appId: '1:1022467481119:web:101600182792e315533f2a',
    messagingSenderId: '1022467481119',
    projectId: 'resikuu-7f832',
    authDomain: 'resikuu-7f832.firebaseapp.com',
    storageBucket: 'resikuu-7f832.firebasestorage.app',
    measurementId: 'G-KP2MTKXZ4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzeZPQ5yGAnJx3HJ7Ywg47nD-rw6d0EIk',
    appId: '1:1022467481119:android:71941afd9c8b5e70533f2a',
    messagingSenderId: '1022467481119',
    projectId: 'resikuu-7f832',
    storageBucket: 'resikuu-7f832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFU46uDEK3itzo6KYFqI5goUguu-PPg-Q',
    appId: '1:1022467481119:ios:056b5b4911e99954533f2a',
    messagingSenderId: '1022467481119',
    projectId: 'resikuu-7f832',
    storageBucket: 'resikuu-7f832.firebasestorage.app',
    iosBundleId: 'com.example.resikuu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFU46uDEK3itzo6KYFqI5goUguu-PPg-Q',
    appId: '1:1022467481119:ios:056b5b4911e99954533f2a',
    messagingSenderId: '1022467481119',
    projectId: 'resikuu-7f832',
    storageBucket: 'resikuu-7f832.firebasestorage.app',
    iosBundleId: 'com.example.resikuu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJLMQEXpqyWLVssWyDmlYoNXs0ZD9WkqA',
    appId: '1:1022467481119:web:25ae3cea2f0d509a533f2a',
    messagingSenderId: '1022467481119',
    projectId: 'resikuu-7f832',
    authDomain: 'resikuu-7f832.firebaseapp.com',
    storageBucket: 'resikuu-7f832.firebasestorage.app',
    measurementId: 'G-N6NYJKMLH4',
  );
}
